name: ask_ai_app
description: Flutter app that simulates a conversation with an AI assistant
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.41.7

dependencies:
  app_ui:
    path: packages/app_ui
  bloc: ^9.2.0
  chat_client:
    path: packages/chat_client/chat_client
  chat_repository:
    path: packages/chat_repository
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  web_socket_chat_client:
    path: packages/chat_client/web_socket_chat_client

dev_dependencies:
  bloc_lint: ^0.4.1
  bloc_test: ^10.0.0
  bloc_tools: ^0.1.0-dev.23
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  very_good_analysis: ^10.2.0

flutter:
  generate: true
  uses-material-design: true
